pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                git branch: 'main', url: 'https://github.com/armphanu/Software-Development-Tools-And-Environments-Group11.git'
            }
        }
        stage('Download dependency') {
            steps {
                sh '''cd front-end
                npm install'''
            }
        }
        stage('Scan code with Lint') {
            steps {
                sh '''cd front-end
                npm run lint'''
            }
        }
        stage('Run unit test and code coverage') {
            steps {
                sh '''cd front-end
                npm run test:unit'''
            }
 
        }

        stage('Run component test') {
            steps {
                    sh '''cd front-end
                    npm run component_test'''
            }
        }
        stage('Run E2E test') {
            steps {
                    sh '''cd front-end
                    npm run e2e_test'''
            }
        }
        stage('Build') {
            steps {
                    sh '''cd front-end
                    npm run build'''
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy'
            }
        }
        stage('Notification') {
            steps {
                echo 'All Stage pass'
            }
        }
    }
}
