pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                checkout scm
            }
        }
        stage('Download dependency') {
            steps {
                sh '''cd back-end
                npm install'''
            }
        }
        stage('Run unit test') {
            steps {
                    sh '''cd back-end
                    rm -rf coverage_unit
                    rm -rf test-report_unit.html
                    npm i jest-html-reporter
                    npm test -- unit.test.js
                    mv  coverage coverage_unit
                    mv  test-report.html test-report_unit.html
                    cd coverage_unit
                    mv  clover.xml clover_unit.xml
                    '''
            }
        }
        stage('Create code coverage unit test') {
            steps {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'back-end/coverage_unit/lcov-report', reportFiles: 'index.html', reportName: 'unit code coverage Report', reportTitles: 'unit code coverage Report'])
            }
 
        }
        stage('Create test report unit test') {
            steps {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'back-end', reportFiles: 'test-report_unit.html', reportName: 'unit Test Report', reportTitles: 'unit Test Report'])
            }
 
        }

        stage('Run component test') {
            steps {
                    sh '''cd back-end
                    npm test -- handler.test.js'''
            }
        }
        
        stage('Create code coverage component test') {
            steps {
                    clover(cloverReportDir: 'back-end/coverage', cloverReportFileName: 'clover.xml',
                    healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
                    unhealthyTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0],
                    failingTarget: [methodCoverage: 0, conditionalCoverage: 0, statementCoverage: 0]
                )
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'back-end/coverage/lcov-report', reportFiles: 'index.html', reportName: 'component code coverage Report', reportTitles: 'component code coverage Report'])
            }
 
        }
        stage('Create test report component test') {
            steps {
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: true, reportDir: 'back-end', reportFiles: 'test-report.html', reportName: 'component Test Report', reportTitles: 'component Test Report'])
            }
 
        }
        stage('Build push pull&deploy docker') {
            steps {
                withCredentials([
                usernamePassword(credentialsId: 'team11-frontend', passwordVariable: 'password', usernameVariable: 'userName'), 
                string(credentialsId: 'host_back-team11', variable: 'host'), string(credentialsId: 'name-team11', variable: 'name'), 
                usernamePassword(credentialsId: 'docker-hub-team11', passwordVariable: 'dockerpassword', usernameVariable: 'dockerusername')]){
                    script{
                        def remote = [:]
                        remote.name = name
                        remote.host = host
                        remote.user = userName
                        remote.password = password
                        remote.allowAnyHosts = true
                        sshCommand remote: remote, command: "git clone -b matching_post https://github.com/armphanu/Software-Development-Tools-And-Environments-Group11.git"
                        sshCommand remote: remote, command: "docker-compose -f Software-Development-Tools-And-Environments-Group11/docker-compose-build.yml build backtend"
                        
                        
                        sshCommand remote: remote, command: "docker login -u $dockerusername -p $dockerpassword"
                        sshCommand remote: remote, command: "docker push armphanu/team-11-backend:1.0.0"
                        sshCommand remote: remote, command: "docker rmi armphanu/team-11-backend:1.0.0"
                        
                        


                    }
                }

            }
            post{
                failure{
                    script{
                        def testing = build job: "team-11-frontend"
                        sh '$testing.getNumber()'
                    }
                    withCredentials([gitUsernamePassword(credentialsId: '7882d410-36db-40f1-9bd4-80675b0f5556', gitToolName: 'git-tool')]) {
                    sh 'git tag -d ' + '1.0.'+ $testing.getNumber()
                    }
                        
                }
            }
        }
        stage('Notification') {
            steps {
                echo 'All Stage pass'
            }
        }
    }
}